// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ginxlqqcrcckbfmzvmsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpbnhscXFjcmNja2JmbXp2bXNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3Njg5MjksImV4cCI6MjA1NzM0NDkyOX0.I4SKv3W1ulgcT6Xw4Ys2Chsm6CEBe3L39L5dQOGw-W0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);